version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-csgo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: csgo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kotlin-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: csgo
      DB_USER: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
